topic_mapping:
  control_cmd: /awsim/control_cmd
  imu_raw: /sensing/imu/imu_raw
  nav_sat_fix: /sensing/gnss/nav_sat_fix
  scan: /scan
  steering_status: /vehicle/status/steering_status
  velocity_status: /vehicle/status/velocity_status
  pose_with_covariance: /localization/pose_with_covariance

topics:
  control_cmd: true
  imu_raw: true
  nav_sat_fix: true
  scan: true
  steering_status: true
  velocity_status: true
  pose_with_covariance: true

compression:
  complib: blosc:zstd
  complevel: 1
  shuffle: byte

sync:
  reference_topic: /awsim/control_cmd
  tolerance_ms: 50.0
